# Generated by Django 4.1.5 on 2023-01-25 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_api_ozon_profile_ozon_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ozon_keywords',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wb_keywords',
        ),
        migrations.AddField(
            model_name='profile',
            name='ozon_products',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='wb_products',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
