# Generated by Django 4.1.5 on 2023-01-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_profile_ozon_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ozon_products',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wb_products',
            field=models.TextField(blank=True),
        ),
    ]
