# Generated by Django 4.1.5 on 2023-01-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_ozon_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ozon_products',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wb_products',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_user',
            field=models.TextField(),
        ),
    ]
